window:
  decorations: full
  dynamic_padding: false
  position:
    x: 0
    y: 0
  dimensions:
    columns: 293
    lines: 80
shell:
  program: /usr/local/bin/zsh
  args:
    - --login
alt_send_esc: false
live_config_reload: true
font:
  size: 11
  normal:
    family: 'JetBrainsMono Nerd Font Mono'
    style: 'Regular'
  bold:
    family: 'JetBrainsMono Nerd Font Mono'
    style: 'Bold'
  italic:
    family: 'JetBrainsMono Nerd Font Mono'
    style: 'Italic'
  bold_italic:
    family: 'JetBrainsMono Nerd Font Mono'
    style: 'Bold Italic'

  use_thin_strokes: true
  # hack mono 1 and 3
  offset:
    x: 1
    y: 2
  # hack mono 0 and 3
  glyph_offset:
    x: 0
    y: 3
draw_bold_text_with_bright_colors: true
selection:
  save_to_clipboard: false
debug:
  log_level: Trace

colors:
  primary:
    # 101112
    # 1d1f21
    background: '0x1c1d1e'
    foreground: '0xc0c5ce'
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'
