#!/usr/bin/env sh

# global settings
# yabai -m config external_bar                 all:24:0
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_shadow                on
# yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   16

yabai -m space 1 --layout bsp

# rules
## makes system preferences always floating
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^licecap$" manage=off

yabai -m rule --add app="^Tweetbot$" title="^$" manage=off grid=1:4:0:0:1:1
yabai -m rule --add app="^Tweetbot$" title="^Main Window - @tiago$" space=1 grid=1:4:0:0:1:1
yabai -m rule --add app="^Alacritty$" space=3
yabai -m rule --add app="^Spotify$" space=5
yabai -m rule --add app="^Slack$" space=5

yabai -m signal --add event=space_changed action="osascript ~/.dotfiles/change-input-to-us"

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

echo "yabai configuration loaded.."
