add_newline = false

format = """\
          $username\
          $directory\
          $git_branch\
          $git_state\
          $git_status\
          $elixir\
          $rust\
          $terraform\
          $nix_shell\
          $env_var\
          $cmd_duration\
          $custom\
          $jobs\
          $time\
          $character\
          """

[package]
disabled = true

[ruby]
# symbol = "🔺 "

[character]
# symbol = "➜"
error_symbol = "✗"
# use_symbol_for_status = true
